spring.application.name=backend_service

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/ecom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:}
security.excluded.paths=${SECURITY_EXCLUDED_PATHS:/swagger-ui,/v3/api-docs,/auth}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
stripe.api.key=${STRIPE_API_KEY:}
payment.success.url=${PAYMENT_SUCCESS_URL:http://localhost:8080/payment/success}
payment.cancel.url=${PAYMENT_CANCEL_URL:http://localhost:8080/payment/cancel}
payment.currency=${PAYMENT_CURRENCY:inr}
